---
name: "Install Kontrol"
description: "Install Runtime Verification's Kontrol"
branding:
  icon: "inbox"
  color: "yellow"

inputs:
  version:
    description: "Version of Kontrol to install"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: "Install Nix"
      uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
        extra_nix_config: |
          substituters = http://cache.nixos.org https://cache.iog.io https://k-framework.cachix.org https://k-framework-binary.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= k-framework.cachix.org-1:jeyMXB2h28gpNRjuVkehg+zLj62ma1RnyyopA/20yFE=

    - name: 'Install Cachix'
      uses: cachix/cachix-action@v14

    - name: "Install Kup"
      shell: bash
      run: |
        bash <(curl https://kframework.org/install)

    - name: "Install Kontrol Latest"
      if: ${{ inputs.version == 'latest' }} 
      shell: bash
      run: |
        kup install kontrol

    - name: "Install Kontrol Version: ${{ inputs.version }}"
      if: ${{ inputs.version != 'latest' }}
      shell: bash
      run: |
        kup install kontrol --version ${{ inputs.version }}
