---
  name: "Test Installation of KaaS-CLI"
  on:
    pull_request:
      branches:
        - main

    workflow_dispatch:
  jobs:
    lint:
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{ github.token }}
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install actionlint
        run: |
          gh extension install https://github.com/cschleiden/gh-actionlint
  
      - name: Run actionlint
        run: |
          gh actionlint -verbose -color
          gh actionlint -verbose -color ./action.yaml

    install-latest:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
          with:
            version: latest

    install-no-parameter:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
            
    install-specific:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
          with:
            version: v0.1.227
  
        - name: Test kaas-cli
          shell: bash
          run: |
            kaas-cli --help

    dummy-proof-check:
      runs-on: [ubuntu-latest]
      needs: [install-latest, install-no-parameter, install-specific]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Kontrol
          uses: ./
          with:
            version: latest

        - name: Checkout Audit Template
          uses: actions/checkout@v4
          with:
            repository: "runtimeverification/audit-kontrol-template"
            ref: "master"
            path: "kontrol-template"

        - name: Dummy Proof Check
          shell: bash
          working-directory: kontrol-template
          run: |
            echo "Dummy Proof Check"
            ./kontrol/run-kontrol.sh