---
  name: "Test Install Kontrol"
  on:
    pull_request:
      branches:
        - main

    workflow_dispatch:
  jobs:
    lint:
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{ github.token }}
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install actionlint
        run: |
          gh extension install https://github.com/cschleiden/gh-actionlint
  
      - name: Run actionlint
        run: |
          gh actionlint -verbose -color

    install-latest:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
          with:
            version: latest
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}

        - name: Test Kontrol Version
          shell: bash
          run: |
            kontrol version

    install-no-parameter:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
          with:
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}
  
        - name: Test Kontrol Version
          shell: bash
          run: |
            kontrol version

    install-specific:
      runs-on: [ubuntu-latest]
      needs: [lint]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Use Install Kontrol Action
          uses: ./
          with:
            version: v0.1.227
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}
  
        - name: Test Kontrol Version
          shell: bash
          run: |
            kontrol version

    dummy-proof-check:
      runs-on: [ubuntu-latest]
      needs: [install-latest, install-no-parameter, install-specific]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Kontrol
          uses: ./
          with:
            version: latest
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
    
        - name: Checkout Audit Template
          uses: actions/checkout@v4
          with:
            repository: "runtimeverification/audit-kontrol-template"
            ref: "master"
            path: "kontrol-template"
            token: ${{ secrets.JENKINS_GITHUB_PAT }}

        - name: Dummy Proof Check
          shell: bash
          working-directory: kontrol-template
          run: |
            echo "Dummy Proof Check"
            ./kontrol/run-kontrol.sh dev
