name: Lint Action

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install actionlint
      run: |
        gh extension install https://github.com/cschleiden/gh-actionlint

    - name: Run actionlint
      run: |
        gh actionlint -verbose -color
        gh actionlint -verbose -color ./action.yaml